/**
 * Generated by Agitar build: AgitarOne Version 6.0.0.000018 (Build date: Sep 06, 2013) [6.0.0.000018]
 * JDK Version: 1.6.0_14
 *
 * Generated on 2014-3-11 13:25:36
 * Time to generate: 00:10.563 seconds
 *
 *
 * agitar.src.md5=com.huawei.ism.openapi.common.exception.ApiException:0a1277702f57b1a15d67a24cd4db2fe6
 *
 */

package com.huawei.ism.openapi.common.exception;

import com.agitar.lib.junit.AgitarTestCase;

public class ApiExceptionAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return ApiException.class;
    }
    
    public void testConstructor() throws Throwable {
        ApiMessage msg = new ApiMessage(100L, "testApiExceptionErrDescription", "testApiExceptionErrSuggestion");
        ApiException apiException = new ApiException(msg);
        assertSame("apiException.getErrMessage()", msg, apiException.getErrMessage());
        assertEquals("apiException.getMessage()", "testApiExceptionErrDescription", apiException.getMessage());
    }
    
    public void testConstructor1() throws Throwable {
        ApiMessage msg = new ApiMessage(100L, "testApiExceptionErrDescription", "testApiExceptionErrSuggestion");
        Exception e = new ApiException(msg);
        ApiMessage msg2 = new ApiMessage(1000L, "testApiExceptionErrDescription1", "testApiExceptionErrSuggestion1");
        ApiException apiException = new ApiException(msg2, e);
        assertSame("apiException.getErrMessage()", msg2, apiException.getErrMessage());
        assertSame("apiException.getException()", e, apiException.getException());
        assertEquals("apiException.getMessage()", "testApiExceptionErrDescription1", apiException.getMessage());
    }
    
    public void testGetErrMessage() throws Throwable {
        ApiMessage msg = new ApiMessage(100L, "testApiExceptionErrDescription", "testApiExceptionErrSuggestion");
        ApiMessage result = new ApiException(msg).getErrMessage();
        assertSame("result", msg, result);
    }
    
    public void testSetException() throws Throwable {
        Exception e = new ClassNotFoundException();
        ApiMessage msg = new ApiMessage(100L, "testApiExceptionErrDescription", "testApiExceptionErrSuggestion");
        ApiException apiException = new ApiException(msg, e);
        apiException.setException(e);
        assertSame("apiException.getException()", e, apiException.getException());
    }
    
    public void testConstructorThrowsNullPointerException() throws Throwable {
        try {
            new ApiException(null);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(ApiException.class, ex);
        }
    }
    
    public void testConstructorThrowsNullPointerException1() throws Throwable {
        try {
            new ApiException(null, new Exception());
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(ApiException.class, ex);
        }
    }
}

